### ISSUE TITLE
Bug: API https://api.nuxtjs.dev/mountains is not working

### ISSUE THREAD

**Issue by karloespiritu** [nuxt-academy/examples#2]
The API endpoint used in the SEO example is not working:

<img width="636" alt="Screen Shot 2021-04-23 at 1 11 30 AM" src="https://user-images.githubusercontent.com/219083/115756845-e1197880-a3d0-11eb-9b24-7531236a0ba6.png">

**Comment by atinux** [comment]
Should be fixed, sorry for the delay :grimacing:
